name: BedrockHandler
version: ${project.version}
main: com.github.retropronghorn.bedrockhandler.BedrockHandler
api-version: 1.13
authors: [RetroPronghorn]
description: Take action when a bedrock client joins the server
website: https://github.com/retropronghorn
depend: [floodgate]
softdepend: [LuckPerms]